### ISSUE TITLE
Cannot upgrade WalletConnect 1.11.1

### ISSUE THREAD

**Issue by peterpeterparker** [dfinity/oisy-wallet#1033]
Latest walletconnect upgrade issue.

```
x Build failed in 9.44s
x Build failed in 12.02s
error during build:
RollupError: [vite-plugin-sveltekit-compile] node_modules/@walletconnect/core/node_modules/@walletconnect/logger/dist/index.es.js (1:132): "Writable" is not exported by "__vite-browser-external", imported by "node_modules/@walletconnect/core/node_modules/@walletconnect/logger/dist/index.es.js".
file: /Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/@walletconnect/core/node_modules/@walletconnect/logger/dist/index.es.js:1:132
1: import h,{levels as i}from"pino";import{default as D}from"pino";import{safeJsonStringify as u}from"@walletconnect/safe-json";import{Writable a...
                                                                                                                                       ^
2: //# sourceMappingURL=index.es.js.map
file: /Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/@walletconnect/core/node_modules/@walletconnect/logger/dist/index.es.js:1:132
1: import h,{levels as i}from"pino";import{default as D}from"pino";import{safeJsonStringify as u}from"@walletconnect/safe-json";import{Writable a...
                                                                                                                                       ^
2: //# sourceMappingURL=index.es.js.map
    at getRollupError (file:///Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at error (file:///Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
    at Module.error (file:///Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/rollup/dist/es/shared/node-entry.js:13688:16)
    at Module.traceVariable (file:///Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/rollup/dist/es/shared/node-entry.js:14136:29)
    at ModuleScope.findVariable (file:///Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/rollup/dist/es/shared/node-entry.js:11817:39)
    at ChildScope.findVariable (file:///Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/rollup/dist/es/shared/node-entry.js:6037:38)
    at Identifier.bind (file:///Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/rollup/dist/es/shared/node-entry.js:7311:40)
    at ClassDeclaration.bind (file:///Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/rollup/dist/es/shared/node-entry.js:4753:23)
    at Program.bind (file:///Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/rollup/dist/es/shared/node-entry.js:4749:28)
    at Module.bindReferences (file:///Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/rollup/dist/es/shared/node-entry.js:13669:18)
```

Reported  👉 https://github.com/WalletConnect/walletconnect-monorepo/issues/4414

**Comment by peterpeterparker** [comment]
Issue has been patched in `@walletconnect/logger`.
