### ISSUE TITLE
Local devevelopment issue with Wallet Connect

### ISSUE THREAD

**Issue by peterpeterparker** [dfinity/oisy-wallet#478]
Wallet Connect is fine on mainnet however, locally when developing we are facing following issue when connecting as of `@walletconnect/web3wallet@1.9.3`.

> {context: 'core'} {context: 'core/relayer'} {context: 'core/relayer/subscription'} TypeError: this.events.off is not a function
>    at Ot.off (index.ts:5:16)
>    at EventEmitter.a2 (index.ts:5:16)
>    at emitOne (node-modules-polyfills:events:89:20)
>    at EventEmitter.emit (node-modules-polyfills:events:171:7)
>    at Ot.addSubscription (index.ts:5:16)
 >   at Ot.setSubscription (index.ts:5:16)
>    at Ot.onSubscribe (index.ts:5:16)
>    at Ot.subscribe (index.ts:5:16)
>    at async index.ts:5:16

As a workaround we stick to `@walletconnect/web3wallet@1.9.1` for now.

**Comment by peterpeterparker** [comment]
Related WC issue: https://github.com/WalletConnect/walletconnect-monorepo/issues/3913

**Comment by peterpeterparker** [comment]
WalletConnect has close the bug and won't proceed debugging it until someone provides a sample repo.

**Comment by peterpeterparker** [comment]
I provided a sample repo and opened a new issue to share my findings: https://github.com/WalletConnect/walletconnect-monorepo/issues/4064

There is an issue with the WalletConnect library and Node polyfill.

**Comment by peterpeterparker** [comment]
"Resolved" in #549 by removing the polyfier in #545
